# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hokuyo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amberdriver.common import drivermsg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hokuyo.proto',
  package='amber.hokuyo_proto',
  serialized_pb=_b('\n\x0chokuyo.proto\x12\x12\x61mber.hokuyo_proto\x1a\x0f\x64rivermsg.proto\"1\n\x04Scan\x12\x12\n\x06\x61ngles\x18\x01 \x03(\x01\x42\x02\x10\x01\x12\x15\n\tdistances\x18\x02 \x03(\x05\x42\x02\x10\x01:)\n\x0fget_single_scan\x12\x10.amber.DriverMsg\x18( \x01(\x08:8\n\x04scan\x12\x10.amber.DriverMsg\x18) \x01(\x0b\x32\x18.amber.hokuyo_proto.Scan:)\n\x0f\x65nable_scanning\x12\x10.amber.DriverMsg\x18* \x01(\x08:#\n\ttimestamp\x12\x10.amber.DriverMsg\x18\x31 \x01(\x02\x42,\n\x1dpl.edu.agh.amber.hokuyo.protoB\x0bHokuyoProto')
  ,
  dependencies=[drivermsg_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


GET_SINGLE_SCAN_FIELD_NUMBER = 40
get_single_scan = _descriptor.FieldDescriptor(
  name='get_single_scan', full_name='amber.hokuyo_proto.get_single_scan', index=0,
  number=40, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
SCAN_FIELD_NUMBER = 41
scan = _descriptor.FieldDescriptor(
  name='scan', full_name='amber.hokuyo_proto.scan', index=1,
  number=41, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ENABLE_SCANNING_FIELD_NUMBER = 42
enable_scanning = _descriptor.FieldDescriptor(
  name='enable_scanning', full_name='amber.hokuyo_proto.enable_scanning', index=2,
  number=42, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
TIMESTAMP_FIELD_NUMBER = 49
timestamp = _descriptor.FieldDescriptor(
  name='timestamp', full_name='amber.hokuyo_proto.timestamp', index=3,
  number=49, type=2, cpp_type=6, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SCAN = _descriptor.Descriptor(
  name='Scan',
  full_name='amber.hokuyo_proto.Scan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angles', full_name='amber.hokuyo_proto.Scan.angles', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='distances', full_name='amber.hokuyo_proto.Scan.distances', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['Scan'] = _SCAN
DESCRIPTOR.extensions_by_name['get_single_scan'] = get_single_scan
DESCRIPTOR.extensions_by_name['scan'] = scan
DESCRIPTOR.extensions_by_name['enable_scanning'] = enable_scanning
DESCRIPTOR.extensions_by_name['timestamp'] = timestamp

Scan = _reflection.GeneratedProtocolMessageType('Scan', (_message.Message,), dict(
  DESCRIPTOR = _SCAN,
  __module__ = 'hokuyo_pb2'
  # @@protoc_insertion_point(class_scope:amber.hokuyo_proto.Scan)
  ))
_sym_db.RegisterMessage(Scan)

drivermsg_pb2.DriverMsg.RegisterExtension(get_single_scan)
scan.message_type = _SCAN
drivermsg_pb2.DriverMsg.RegisterExtension(scan)
drivermsg_pb2.DriverMsg.RegisterExtension(enable_scanning)
drivermsg_pb2.DriverMsg.RegisterExtension(timestamp)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035pl.edu.agh.amber.hokuyo.protoB\013HokuyoProto'))
_SCAN.fields_by_name['angles'].has_options = True
_SCAN.fields_by_name['angles']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SCAN.fields_by_name['distances'].has_options = True
_SCAN.fields_by_name['distances']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
