# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collision_avoidance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amberdriver.common import drivermsg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='collision_avoidance.proto',
  package='amber.collision_avoidance_proto',
  serialized_pb=_b('\n\x19\x63ollision_avoidance.proto\x12\x1f\x61mber.collision_avoidance_proto\x1a\x0f\x64rivermsg.proto\"m\n\x0bMotorsSpeed\x12\x16\n\x0e\x66rontLeftSpeed\x18\x01 \x01(\x05\x12\x17\n\x0f\x66rontRightSpeed\x18\x02 \x01(\x05\x12\x15\n\rrearLeftSpeed\x18\x03 \x01(\x05\x12\x16\n\x0erearRightSpeed\x18\x04 \x01(\x05\"1\n\x04Scan\x12\x12\n\x06\x61ngles\x18\x01 \x03(\x01\x42\x02\x10\x01\x12\x15\n\tdistances\x18\x02 \x03(\x05\x42\x02\x10\x01:\"\n\x08setSpeed\x12\x10.amber.DriverMsg\x18Z \x01(\x08:\"\n\x08getSpeed\x12\x10.amber.DriverMsg\x18[ \x01(\x08:)\n\x0fgetSpeedAndScan\x12\x10.amber.DriverMsg\x18\\ \x01(\x08:!\n\x07getScan\x12\x10.amber.DriverMsg\x18] \x01(\x08:S\n\x0bmotorsSpeed\x12\x10.amber.DriverMsg\x18^ \x01(\x0b\x32,.amber.collision_avoidance_proto.MotorsSpeed:E\n\x04scan\x12\x10.amber.DriverMsg\x18_ \x01(\x0b\x32%.amber.collision_avoidance_proto.ScanBD\n)pl.edu.agh.amber.collisionavoidance.protoB\x17\x43ollisionAvoidanceProto')
  ,
  dependencies=[drivermsg_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


SETSPEED_FIELD_NUMBER = 90
setSpeed = _descriptor.FieldDescriptor(
  name='setSpeed', full_name='amber.collision_avoidance_proto.setSpeed', index=0,
  number=90, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
GETSPEED_FIELD_NUMBER = 91
getSpeed = _descriptor.FieldDescriptor(
  name='getSpeed', full_name='amber.collision_avoidance_proto.getSpeed', index=1,
  number=91, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
GETSPEEDANDSCAN_FIELD_NUMBER = 92
getSpeedAndScan = _descriptor.FieldDescriptor(
  name='getSpeedAndScan', full_name='amber.collision_avoidance_proto.getSpeedAndScan', index=2,
  number=92, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
GETSCAN_FIELD_NUMBER = 93
getScan = _descriptor.FieldDescriptor(
  name='getScan', full_name='amber.collision_avoidance_proto.getScan', index=3,
  number=93, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MOTORSSPEED_FIELD_NUMBER = 94
motorsSpeed = _descriptor.FieldDescriptor(
  name='motorsSpeed', full_name='amber.collision_avoidance_proto.motorsSpeed', index=4,
  number=94, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
SCAN_FIELD_NUMBER = 95
scan = _descriptor.FieldDescriptor(
  name='scan', full_name='amber.collision_avoidance_proto.scan', index=5,
  number=95, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_MOTORSSPEED = _descriptor.Descriptor(
  name='MotorsSpeed',
  full_name='amber.collision_avoidance_proto.MotorsSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frontLeftSpeed', full_name='amber.collision_avoidance_proto.MotorsSpeed.frontLeftSpeed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frontRightSpeed', full_name='amber.collision_avoidance_proto.MotorsSpeed.frontRightSpeed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rearLeftSpeed', full_name='amber.collision_avoidance_proto.MotorsSpeed.rearLeftSpeed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rearRightSpeed', full_name='amber.collision_avoidance_proto.MotorsSpeed.rearRightSpeed', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=188,
)


_SCAN = _descriptor.Descriptor(
  name='Scan',
  full_name='amber.collision_avoidance_proto.Scan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angles', full_name='amber.collision_avoidance_proto.Scan.angles', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='distances', full_name='amber.collision_avoidance_proto.Scan.distances', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=239,
)

DESCRIPTOR.message_types_by_name['MotorsSpeed'] = _MOTORSSPEED
DESCRIPTOR.message_types_by_name['Scan'] = _SCAN
DESCRIPTOR.extensions_by_name['setSpeed'] = setSpeed
DESCRIPTOR.extensions_by_name['getSpeed'] = getSpeed
DESCRIPTOR.extensions_by_name['getSpeedAndScan'] = getSpeedAndScan
DESCRIPTOR.extensions_by_name['getScan'] = getScan
DESCRIPTOR.extensions_by_name['motorsSpeed'] = motorsSpeed
DESCRIPTOR.extensions_by_name['scan'] = scan

MotorsSpeed = _reflection.GeneratedProtocolMessageType('MotorsSpeed', (_message.Message,), dict(
  DESCRIPTOR = _MOTORSSPEED,
  __module__ = 'collision_avoidance_pb2'
  # @@protoc_insertion_point(class_scope:amber.collision_avoidance_proto.MotorsSpeed)
  ))
_sym_db.RegisterMessage(MotorsSpeed)

Scan = _reflection.GeneratedProtocolMessageType('Scan', (_message.Message,), dict(
  DESCRIPTOR = _SCAN,
  __module__ = 'collision_avoidance_pb2'
  # @@protoc_insertion_point(class_scope:amber.collision_avoidance_proto.Scan)
  ))
_sym_db.RegisterMessage(Scan)

drivermsg_pb2.DriverMsg.RegisterExtension(setSpeed)
drivermsg_pb2.DriverMsg.RegisterExtension(getSpeed)
drivermsg_pb2.DriverMsg.RegisterExtension(getSpeedAndScan)
drivermsg_pb2.DriverMsg.RegisterExtension(getScan)
motorsSpeed.message_type = _MOTORSSPEED
drivermsg_pb2.DriverMsg.RegisterExtension(motorsSpeed)
scan.message_type = _SCAN
drivermsg_pb2.DriverMsg.RegisterExtension(scan)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n)pl.edu.agh.amber.collisionavoidance.protoB\027CollisionAvoidanceProto'))
_SCAN.fields_by_name['angles'].has_options = True
_SCAN.fields_by_name['angles']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_SCAN.fields_by_name['distances'].has_options = True
_SCAN.fields_by_name['distances']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
