# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amber.common import drivermsg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dummy.proto',
  package='amber.dummy_proto',
  serialized_pb=_b('\n\x0b\x64ummy.proto\x12\x11\x61mber.dummy_proto\x1a\x0f\x64rivermsg.proto: \n\x06\x65nable\x12\x10.amber.DriverMsg\x18\x32 \x01(\x08:!\n\x07message\x12\x10.amber.DriverMsg\x18\x33 \x01(\t:$\n\nget_status\x12\x10.amber.DriverMsg\x18\x34 \x01(\x08\x42*\n\x1cpl.edu.agh.amber.driver.dummy.protoB\nDummyProto')
  ,
  dependencies=[drivermsg_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


ENABLE_FIELD_NUMBER = 50
enable = _descriptor.FieldDescriptor(
  name='enable', full_name='amber.dummy_proto.enable', index=0,
  number=50, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MESSAGE_FIELD_NUMBER = 51
message = _descriptor.FieldDescriptor(
  name='message', full_name='amber.dummy_proto.message', index=1,
  number=51, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
GET_STATUS_FIELD_NUMBER = 52
get_status = _descriptor.FieldDescriptor(
  name='get_status', full_name='amber.dummy_proto.get_status', index=2,
  number=52, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['enable'] = enable
DESCRIPTOR.extensions_by_name['message'] = message
DESCRIPTOR.extensions_by_name['get_status'] = get_status

drivermsg_pb2.DriverMsg.RegisterExtension(enable)
drivermsg_pb2.DriverMsg.RegisterExtension(message)
drivermsg_pb2.DriverMsg.RegisterExtension(get_status)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034pl.edu.agh.amber.driver.dummy.protoB\nDummyProto'))
# @@protoc_insertion_point(module_scope)
