# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roboclaw.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


from amber.common import drivermsg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roboclaw.proto',
  package='amber.roboclaw_proto',
  serialized_pb='\n\x0eroboclaw.proto\x12\x14\x61mber.roboclaw_proto\x1a\x0f\x64rivermsg.proto\"m\n\x0bMotorsSpeed\x12\x16\n\x0e\x66rontLeftSpeed\x18\x01 \x01(\x05\x12\x17\n\x0f\x66rontRightSpeed\x18\x02 \x01(\x05\x12\x15\n\rrearLeftSpeed\x18\x03 \x01(\x05\x12\x16\n\x0erearRightSpeed\x18\x04 \x01(\x05:J\n\rmotorsCommand\x12\x10.amber.DriverMsg\x18\n \x01(\x0b\x32!.amber.roboclaw_proto.MotorsSpeed:-\n\x13\x63urrentSpeedRequest\x12\x10.amber.DriverMsg\x18\x0b \x01(\x08:I\n\x0c\x63urrentSpeed\x12\x10.amber.DriverMsg\x18\x0c \x01(\x0b\x32!.amber.roboclaw_proto.MotorsSpeedB6\n%pl.edu.agh.amber.amber.roboclaw.protoB\rRoboclawProto')


MOTORSCOMMAND_FIELD_NUMBER = 10
motorsCommand = _descriptor.FieldDescriptor(
  name='motorsCommand', full_name='amber.roboclaw_proto.motorsCommand', index=0,
  number=10, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
CURRENTSPEEDREQUEST_FIELD_NUMBER = 11
currentSpeedRequest = _descriptor.FieldDescriptor(
  name='currentSpeedRequest', full_name='amber.roboclaw_proto.currentSpeedRequest', index=1,
  number=11, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
CURRENTSPEED_FIELD_NUMBER = 12
currentSpeed = _descriptor.FieldDescriptor(
  name='currentSpeed', full_name='amber.roboclaw_proto.currentSpeed', index=2,
  number=12, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_MOTORSSPEED = _descriptor.Descriptor(
  name='MotorsSpeed',
  full_name='amber.roboclaw_proto.MotorsSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frontLeftSpeed', full_name='amber.roboclaw_proto.MotorsSpeed.frontLeftSpeed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frontRightSpeed', full_name='amber.roboclaw_proto.MotorsSpeed.frontRightSpeed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rearLeftSpeed', full_name='amber.roboclaw_proto.MotorsSpeed.rearLeftSpeed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rearRightSpeed', full_name='amber.roboclaw_proto.MotorsSpeed.rearRightSpeed', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['MotorsSpeed'] = _MOTORSSPEED

class MotorsSpeed(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOTORSSPEED

  # @@protoc_insertion_point(class_scope:amber.roboclaw_proto.MotorsSpeed)

motorsCommand.message_type = _MOTORSSPEED
drivermsg_pb2.DriverMsg.RegisterExtension(motorsCommand)
drivermsg_pb2.DriverMsg.RegisterExtension(currentSpeedRequest)
currentSpeed.message_type = _MOTORSSPEED
drivermsg_pb2.DriverMsg.RegisterExtension(currentSpeed)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n%pl.edu.agh.amber.amber.roboclaw.protoB\rRoboclawProto')
# @@protoc_insertion_point(module_scope)
