# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drive_to_point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amber.common import drivermsg_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='drive_to_point.proto',
  package='amber.drive_to_point_proto',
  serialized_pb=_b('\n\x14\x64rive_to_point.proto\x12\x1a\x61mber.drive_to_point_proto\x1a\x0f\x64rivermsg.proto\"+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01r\x18\x03 \x01(\x01: \n\x06\x65nable\x12\x10.amber.DriverMsg\x18P \x01(\x08:F\n\x06target\x12\x10.amber.DriverMsg\x18Q \x01(\x0b\x32$.amber.drive_to_point_proto.Position:\x1f\n\x05\x63heck\x12\x10.amber.DriverMsg\x18R \x01(\x08\x42\x38\n#pl.edu.agh.amber.drivetopoint.protoB\x11\x44riveToPointProto')
  ,
  dependencies=[drivermsg_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


ENABLE_FIELD_NUMBER = 80
enable = _descriptor.FieldDescriptor(
  name='enable', full_name='amber.drive_to_point_proto.enable', index=0,
  number=80, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
TARGET_FIELD_NUMBER = 81
target = _descriptor.FieldDescriptor(
  name='target', full_name='amber.drive_to_point_proto.target', index=1,
  number=81, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
CHECK_FIELD_NUMBER = 82
check = _descriptor.FieldDescriptor(
  name='check', full_name='amber.drive_to_point_proto.check', index=2,
  number=82, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='amber.drive_to_point_proto.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='amber.drive_to_point_proto.Position.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='amber.drive_to_point_proto.Position.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='amber.drive_to_point_proto.Position.r', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.extensions_by_name['enable'] = enable
DESCRIPTOR.extensions_by_name['target'] = target
DESCRIPTOR.extensions_by_name['check'] = check

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'drive_to_point_pb2'
  # @@protoc_insertion_point(class_scope:amber.drive_to_point_proto.Position)
  ))
_sym_db.RegisterMessage(Position)

drivermsg_pb2.DriverMsg.RegisterExtension(enable)
target.message_type = _POSITION
drivermsg_pb2.DriverMsg.RegisterExtension(target)
drivermsg_pb2.DriverMsg.RegisterExtension(check)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#pl.edu.agh.amber.drivetopoint.protoB\021DriveToPointProto'))
# @@protoc_insertion_point(module_scope)
